version: '3.9'

services:
  android-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartsip-android-dev
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
