version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build-and-release:
    docker:
      - image: cimg/android:2023.12
    steps:
      - checkout
      - run: ./gradlew assembleRelease
      - run:
          name: Upload to Play Store
          command: |
            echo $PLAY_STORE_JSON > service_account.json
            ./gradlew publishRelease
    environment:
      PLAY_STORE_JSON: ${{ secrets.PLAY_STORE_JSON }}

workflows:
  release:
    jobs:
      - build-and-release
