version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2023.11
    working_directory: ~/project

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Grant Gradle permissions
          command: chmod +x ./gradlew
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
