project_id = "tfgcrhmuoinnfiwgibpp"
[auth]
enable_email_signup = true
enable_oauth_signup = true
external.google.enabled = true
external.microsoft.enabled = true
external.apple.enabled = true
external.facebook.enabled = true
